version: '3.4'

services:
  api:
    image: ${DOCKER_REGISTRY-}g2dkapi
    container_name: g2-dk-api
    restart: always
    build:
      context: .
      dockerfile: src/G2.DK.Api/Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    depends_on:
      - db
    networks:
      - backtier

  client:
    image: ${DOCKER_REGISTRY-}g2dkclient
    container_name: g2-dk-client
    restart: always
    build:
      context: ./src/G2-DK-Client
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    networks:
      - backtier

  db:
    image: "mcr.microsoft.com/mssql/server"
    container_name: g2-dk-mssql
    restart: always
    ports:
      - "1433:1433"
    environment:
      SA_PASSWORD: "test$$123"
      ACCEPT_EULA: "Y"
    networks:
      - backtier

  nginx:
    image: ${DOCKER_REGISTRY-}nginx
    container_name: g2-dk-nginx
    restart: always
    build:
      context: ./src/G2-DK-Nginx
      dockerfile: Dockerfile
    ports:
      - "81:80"
    depends_on:
      - api
      - client
    networks:
      - backtier
  
networks:
  backtier:
    driver: bridge
